### ISSUE TITLE
Create all Posts-service's endpoints as not implemented

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#10]
### Story
Add all endpoints from Swagger documentation, which has already been agreed upon, returning `501 not implemented` as a response
Following an iterative method for implementation, we will start adding all endpoints to Posts-service's controller as not yet implemented endpoints.

### Prerequisites
None

### Tasks
- [x] `/posts`
  - [x] `POST` on `/posts`
  - [x] `GET` on `/posts`
  - [x] `GET` on `/posts/{postid}`
  - [x] `PATCH` on `/posts/{postid}`
  - [x] `DELETE` on  `/posts/{postid}`

### Acceptance criteria
- Apply all endpoints in the Tasks section
