### ISSUE TITLE
Remove mocks and don't deploy it.

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#106]
### Story
- [ ] Remove mock as we don't need to deploy it anymore as to save resources/monety.

### Prerequisites
None.

### Tasks
- [ ] Remove mock and don't deploy it by making the necessary needed changes in the K8s and Github workflows.

### Acceptance criteria
- [ ] Mocks are not deployed any more.

**Comment by amroakmal** [comment]
Has been implemented.
