### ISSUE TITLE
Modify README

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#11]
### Story
- change the README with the requirements in the tasks section below

### Prerequisites
- Sequence diagrams files
- openAPI file

### Tasks
- [ ] Clarify how to use vs-code debug mode with screenshots
- [ ] Remove unnecessary database configuration
- [ ] Remove the unnecessary headers
- [ ] Remove the code areas from extra text
- [ ] Add sequence diagrams 
- [ ] Add swagger definitions

### Acceptance criteria
- meet the above tasks
