### ISSUE TITLE
Remove media when post is removed

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#115]
### Story
- Currently whenever a post is removed, the media does not get removed subsequently. We need to remove all media related to a post in all microservices when a post gets removed. 

### Tasks
- [ ] make sure that cascading works fine and media is removed from media entity in `posts microservice`
- [ ] emit a message broker event with all media id(s) to be removed 
- [ ] another ticket should be added to receive the event in `media microservice` and remove the required data

### Acceptance criteria
- [ ] whenever we try to get a media of a deleted post through calling `GET https://pickify-media-be-dev.pickify.net/api/media/:media_id, it should throw exception that this media is not found
