### ISSUE TITLE
fix openAPI 

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#116]
### Story
- [ ] Post type in post_creation_request in openAPI is not updated. It is made an enum with certain values, however, it should accept any string value
- [ ] `created_options_group` schema in openAPI should have all properties (id & options ) required

### Tasks
- [ ]

### Acceptance criteria
- [ ] whenever the posts.openAPI is updated.
