### ISSUE TITLE
Respond with mock data from endpoints

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#12]
### Story
Add a response of mock data to endpoints of Posts-service's controller.
Iterate over the endpoints that have been previously made as not implemented by adding a response of mock data to them.
This response is to ensure a working relationship between the services and the client using them, without the need to implement endpoints to their smallest detail before giving a proper response as per documentation/contract.

### Prerequisites
- All endpoints are to be made returning a response of `501 not implemented`.

### Tasks
- [ ] Respond with mock response to `POST /posts` as per documentation.
- [ ] Respond with mock posts to `GET /posts` as per documentation.
- [ ] Respond with mock response to `POST /posts/{postid}/groups` as per documentation.
- [ ] Respond with mock response to `GET /posts/{postid}` as per documentation.
- [ ] Respond with mock response to `PATCH /posts/{postid}` as per documentation.
- [ ] Respond with mock response to `DELETE /posts/{postid}` as per documentation.

### Acceptance criteria
- All endpoints on Posts-service's controller must respond with mock data following the documentation response schema.
