### ISSUE TITLE
Update media columns names

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#130]
### Story
- [ ] Change media.url column to be named media.id column, and change all necessary files such as interfaces, and so on.

### Prerequisites
- [ ] None.

### Tasks
- [ ] Change media.url to media.id and all related files
- [ ] Make necessary changes in the openAPI
- [ ] Make necessary changes in the Client_Package
- [ ] Generate new migration corresponding to the needed changes

### Acceptance criteria
- [ ] App works as expected, and all changes are made, and all tasks are done.
