### ISSUE TITLE
Handle post readiness

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#132]
### Story
- [ ] We must change the ready state of the post after all of its media files have been received, processed and saved. After a lot of research and discussions, the best way to handle/solve this is by using `subscriber and listener decorators` in `TypeORM`. 

### Prerequisites
- [ ] Receive the media of the post asynchronously.

### Tasks
- [ ] Handle readiness column/flag/property of the post in which all of its media has been received, processed (if needed) and saved successfully.

### Acceptance criteria
- [ ] The post becomes/marked as ready after receiving all of its media and saving it successfully.

**Comment by amroakmal** [comment]
Has been implemented.
