### ISSUE TITLE
User authentication follow-up

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#136]
### Story
- [ ] currently inside some methods we check for user existence. This is due to the current implementation of authentication. However, this should be removed as we implement firebase authentication. All user validations shouldn't happen inside services. 

### Prerequisites
- [ ] firebase authentication is implemented

### Tasks
- [ ] remove validating user inside `createPost` method in posts.service
- [ ] update all controllers' methods to receive `user` from `req` instead of `userId` from `headers`
- [ ] update all services' methods to receive `user` instead of 'userId` and change what is needed accordingly
- [ ] update all controllers & services tests

### Acceptance criteria
- [ ] whenever users authentication is handled only in guards
