### ISSUE TITLE
rabbitMQ local connection

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#137]
### Story
- [ ] In order to develop locally with rabbitMQ broker, we need to add it to docker compose as found in media microservice and add its link as environment variable. 

### Prerequisites
- [ ] rabbitMQ used in the application

### Tasks
- [ ]

### Acceptance criteria
- [ ] whenever we are able to connect to a local rabbitMQ broker after running it from docker compose file.
