### ISSUE TITLE
Migrate DB data

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#138]
### Story
- [ ] The DB has been migrated from elephantSQL to our own deployed DB cluster. We need to migrate the data from the old one to the new one. We need also to add migration script to add the 6 dummy users. 

### Tasks
- [ ] migrate data from old server to new one
- [ ] add migration script to add the 6 dummy user data in users entity

### Acceptance criteria
- [ ] whenever we have all old data.
