### ISSUE TITLE
Creating a group with only one option is not allowed.

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#140]
### Story
- [ ] It's meaningless to have a group with only one option, logically its not with the business/main functionality of Pickify.

### Prerequisites
- [ ] Make sure groups are created successfully and you're able to add options to a certain group.

### Tasks
- [ ] Allow any group to must have at least two options.

### Acceptance criteria
- [ ] App works well, validations are maintained and any group to be created must have at least two options.
