### ISSUE TITLE
openAPI not rendering and gives error on development branch

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#144]
### Story
- [ ] While being on the development branch, the openAPI file is not rendering correctly, there's a problem in it. I tried rendering it locally and on an online editor but both gave an error.

### Prerequisites
- [ ]

### Tasks
- [ ] Make the necessary changes and fixes to make it render correctly.

### Acceptance criteria
- [ ] Rendering the openAPI should work properly as expected.
