### ISSUE TITLE
Migrate RabbitMQ 

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#158]
### Story
- Currently, we use a free RabbitMQ online service. This will have its limitations when the application is in production. We need to connect the app to our own rabbitMQ broker that is deployed on the same k8s cluster 

### Prerequisits
 - [ ] Message broker credentials should be added as secrets

### Tasks
- [ ] Add yaml configuration file for rabbitMQ service
- [ ] Update the environment variables

### Acceptance criteria
- [ ] Whenever the application is connected to the new message broker and receives messages from it.
