### ISSUE TITLE
Endpoint: `GET /posts` - Retrieve feed.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#34]
### Story
Create endpoint for retrieving all posts from database.
No pagination is required for now, just the simplest form of feed response.
Mock data being responded with, as per previous tasks, must be preserved as long as development of this endpoint is in progress.

### Prerequisites
- [ ] All endpoints respond with mock data.

### Tasks
- [ ] Create repository functions for retrieving posts from database.
- [ ] Create service function for retrieving posts, using repository functions made for it.
- [ ] Create controller for `GET /posts`, using the service functions made for it.  

### Acceptance criteria
- `GET /posts` should be returning all posts found in database as per API specs.
