### ISSUE TITLE
Service: Getting feed.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#36]
### Story
After creating needed repository methods, continue implementing `GET /posts` endpoint.
Create service to handle responding with all posts data for the endpoint.

### Prerequisites
- [ ] Repository for getting feed.

### Tasks
- [ ] Create service function for getting feed.
- [ ] Write test file for your code.

### Acceptance criteria
- A working service function that handles responding with posts feed to client.
