### ISSUE TITLE
Controller: Getting feed.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#37]
### Story
After service and repository for feed are done, create controller for `GET /posts`

### Prerequisites
- [ ] Service and repository for getting posts.

### Tasks
- [ ] Create controller function that handles responding with feed for `GET /posts`
- [ ] Write test file for your code.

### Acceptance criteria
- Sending `GET /posts` responds with all posts in database.
