### ISSUE TITLE
Endpoint: `POST /posts` - Post creation.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#38]
### Story
Create endpoint for creating a single post instance in the database.
Mock data being responded with on that endpoint, should be preserved as long as the progress in post creation goes on.

### Prerequisites
- [ ] Respond with mock data from all endpoints.

### Tasks
- [x] Create repository functions for post creation in the database.
- [x] Create service functions for handling calling the right repository functions, and manipulating response as per API specification.
- [x] Create controller function for handling requests on `POST /posts`.

### Acceptance criteria
- Post creation using `POST /post` endpoint should be implemented and working as per API specs.
