### ISSUE TITLE
Endpoint: `POST /posts/{postid}/groups` - Options group.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#39]
### Story
Create endpoint for creating options group in the database.
Mock data being responded with on that endpoint, should be preserved as long as the progress in post creation goes on.

### Tasks
- [ ] Create repository functions for options group creation in the database.
- [ ] Create repository method(s) for adding a new option in Option Entity
- [ ] Create service functions for handling calling the right repository functions, and manipulating response as per API specification.
- [ ] Create controller function for handling requests on `POST /posts/{postid}/groups`.

### Acceptance criteria
- Options group creation using`POST /posts/{postid}/groups`, should be working as per API specs.
