### ISSUE TITLE
Endpoint: `POST /media` - Media creation.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#40]
### Story
Create endpoint for creating media in the database.
Mock data being responded with on that endpoint, should be preserved as long as the progress in post creation goes on.

### Prerequisites
- [ ]  Respond with mock data from all endpoints.

### Tasks
- [ ] Create entity for media creation in the database.
- [ ] Create repository functions for media creation in the database.
- [ ] Create service functions for handling calling the right repository functions, and manipulating response as per API specification.
- [ ] Create controller function for handling requests on `POST /media`.

### Acceptance criteria
- Media creation using `POST /media` endpoint should be implemented and working as per API specs.
