### ISSUE TITLE
Endpoint: `PATCH /posts/{postid}` - Flagging finished posts.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#41]
### Story
Create endpoint for flagging completed posts.
Mock data being responded with on that endpoint, should be preserved as long as the progress in post creation goes on.

### Prerequisites
- [ ] Respond with mock data from all endpoints.

### Tasks
- [ ] Create repository functions for post flagging in the database.
- [ ] Create service functions for handling calling the right repository functions, and manipulating response as per API specification.
- [ ] Create controller function for handling requests on `PATCH /posts/{postid}`.

### Acceptance criteria
- Post flagging using `PATCH /posts/{postid}` endpoint should be implemented and working as per API specs.
