### ISSUE TITLE
Service: Create post.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#43]
### Story
After creating needed repository methods, continue implementing `POST /posts` endpoint.
Create service to handle post creation.

### Prerequisites
- [ ] Repository for post creation.

### Tasks
- [ ] Create service to handle post creation.
- [ ] Create needed DTO's with any needed validations.
- [ ] Write test file for your code.

### Acceptance criteria
- A working service function that handles creation of posts and responding with the right data to client.
