### ISSUE TITLE
Controller: Create post.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#44]
### Story
After service and repository for post creation are done, create controller for `POST /posts`.

### Prerequisites
- [ ] Service for post creation.

### Tasks
- [ ] Create controller function that handles creating post and responding with the right data.
- [ ] Write test file for your code.

### Acceptance criteria
- Creating post on endpoint `POST /posts` works as per API specs.
