### ISSUE TITLE
Entity: Options_Group.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#46]
### Story
To be able to work with groups in the database, and to be able to create and write repository method, we need a group entity.

### Prerequisites
- [ ] Respond with mock data on all endpoints

### Tasks
- [ ] Create options_group entity as per database design.
- [ ] Create its repository

### Acceptance criteria
- when the options_group entity is created in database
