### ISSUE TITLE
Differentiate between used environments such as development env and production env.

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#47]
### Story
We -developers- face errors, and when that occurs we need full information about the error and its stack trace. 
But our users should NOT have any kind or any information about any error if occurred. 
So we need to differentiate between the environment we use as developers, and between the environment that will be available for our users.

### Prerequisites
- [ ] Understand difference between dev env and prod env.
- [ ] Understand why do we need to have several env and what each env is supposed to present/have on certain actions, e.g. when an error occurs, what should logically each env need to present/show.

### Tasks
- [ ] Create development environment
- [ ] Create production environment

### Acceptance criteria
- [ ] Should be able to change between the needed environments. 
- [ ] Each one should have its correct logic presenting what's needed from it.
