### ISSUE TITLE
Add posts microservice diagrams

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#59]
### Story
- Add the diagrams of posts microservice. The diagrams should include ERD and sequence diagrams for the following: post creation, requesting post and voting on an option

### Prerequisites
- none

### Tasks
- [ ] Add ERD for all entities (media, posts, options_groups, options & vote)
- [ ] Add post creation sequence diagram
- [ ] Add requesting posts sequence diagram
- [ ] Add voting sequence diagram

### Acceptance criteria
- When all the sequence diagrams cover all the cases in the posts microservice
