### ISSUE TITLE
Service: Add Media

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#67]
### Story
Create service to handle responding for the addition /creation of new media to the database.

### Prerequisites
- [ ] Repository for handling addition of new media.

### Tasks
- [ ] Create service function for addition /creation of new media.
- [ ] Write test file for your code.

### Acceptance criteria
- A working service function that handles addition/creation of a new media.
