### ISSUE TITLE
Controller: Add Media

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#68]
### Story
After service and repository that handle creation of new media is done, create controller for `POST /media`

### Prerequisites
- [ ] Service and repository for handling creation/addition of a new media.

### Tasks
- [ ] Create controller function that handles responding with feed for `POST /media`
- [ ] Write test file for your code.

### Acceptance criteria
- Sending `POST /media` adds the new media to the database successfully.
