### ISSUE TITLE
Endpoint: POST /api/posts/:postid/groups Implementation

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-posts#77]
### Prerequisites
- [ ] Option Entity
- [ ] Option Repository
- [ ] Options_Group Entity
- [ ] Options_Group Repository

### Tasks
- [ ] Add the interface of the request body (DTO)
- [ ] Add the interface of the response 
- [ ] Add validation for post id parameter & for request body
- [ ] Add the required methods in Option Repository
- [ ] Add tests for Option Repository
- [ ] Add the required methods in Options_group Repository
- [ ] Add tests for Options_Group Repository 
- [ ] Add method in the service provider to act as a liaison between endpoint handle method in controller & repositories
- [ ] Add tests for the service method
- [ ] Add handle method in the controller to make the necessary routes for our endpoint, and to deal with the service provider
- [ ] Add tests for the controller method

### Acceptance criteria
- When sending the required data with validation to POST /api/posts/:postid/groups and receiving the correct response according to the specs.
