### ISSUE TITLE
Endpoint: `DELETE /posts/{postid}` - Post deletion.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#79]
### Story
Create endpoint for deleting post resource and all all post entity related resources: options, option groups, and media.

### Prerequisites
None

### Tasks
- [ ] Create repository functions for post deletion. Keep in mind that deleting posts require deletion of options, option groups, and media related to the post.
- [ ] Create service functions for handling calling the right repository functions, and manipulating response as per API specification.
- [ ] Create controller function for handling requests on `DELETE /posts/{postid}`.
- [ ] Create tests for repository, service, and controller functions.

### Acceptance criteria
A working endpoint for post deletion.
