### ISSUE TITLE
Endpoint: `PUT /votes/{optionid}` - Add Vote.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#81]
### Story
A core element of polls: voting. Add the functionality of voting of options by adding entities, and repository, service, and controller functions for voting logic on options.

### Prerequisites
None.

### Tasks
- [ ] Votes entity.
- [ ] Repository for voting logic, , with respective unit tests.
- [ ] Service for voting logic, with respective unit tests.
- [ ] Controller for `PUT /votes/{optionid}` endpoint, with respective unit tests.

### Acceptance criteria
A working voting functionality on posts.
