### ISSUE TITLE
Create new special workflow 

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/pickify-posts#99]
### Story
- [] Create a new github workflow special for the `receive-media-async` branch and add a new database (elephantSQL) to it.

### Prerequisites
None.

### Tasks
- [ ] Create a new github workflow special for the `receive-media-async` branch.
- [ ] Add elephantSQL_special as a secret for the repository.
- [ ] Add a new database (elephantSQL) to it.

### Acceptance criteria
- [ ] The workflow should work and it will be using the new added secret.
